### ISSUE TITLE
JBD - DC House battery not detected

### ISSUE THREAD

**Issue by mbeeuid** [patman15/BMS_BLE-HA#157]
### Checklist

- [x] I have tried the latest version of BMS_BLE-HA.
- [x] I have enabled debug logging for my installation.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issue](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3Abug).
- [x] I have filled out the issue template to the best of my ability.

### Provide the type of BMS you used:

DC House: DBJBD (JBD) Firmware ver: 6.6 Device: DP04S007L4S120A

### Describe the issue

DC House battery not discovered even though it appears to use a JBD BMS.  I see a new "DCHouse" Branch, will this cover this particular BMS? (155-new-integration-dc-house-12v-lifepo4-battery-with-bluetooth)

### Reproduction steps

```text
1.
2.
3.
...
```

### Debug logs

Battery not found.  (no log)

**Comment by patman15** [comment]
```
Device A5:C2:37:2E:A1:17 (public)         
        Name: DP04S007L4S120A                          
        Alias: DP04S007L4S120A                         
        Paired: no                                     
        Bonded: no                        
        Trusted: no                                    
        Blocked: no                                    
        Connected: no                                  
        LegacyPairing: no                              
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Unknown                   (0000ff00-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (00010203-0405-0607-0809-0a0b0c0d1912)
        Modalias: usb:v248Ap8266d0001                             
        ManufacturerData.Key: 0xa117 (41239)                      
        ManufacturerData.Value:                              
  2e 37 c2 a5                                      .7..
        AdvertisingFlags:                                         
  06                   
```
