### ISSUE TITLE
Any chance to get the Felicity Solar LUX-Y-48300LG01 battery working?

### ISSUE THREAD

**Issue by edelstahlratte** [patman15/BMS_BLE-HA#161]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Please describe the enhancement you would like to have.

I have a Felicity Solar LUX-Y-48300LG01 battery, but it does not get recognised... It has WiFi and BLE connection...

The device name is like F100011002424470238

```
bluetoothctl info A8:17:10:68:8B:46
Unable to open mgmt_socket
Device A8:17:10:68:8B:46 (public)
        Name: F100011002424470238
        Alias: F100011002424470238
        Paired: no
        Bonded: no
        Trusted: no
        Blocked: no
        Connected: no
        LegacyPairing: no
        RSSI: 0xffffffc8 (-56)
        AdvertisingFlags:
  06                            
```

I know nothing about Bluetooth, what else can I provide?

### Additional context

https://play.google.com/store/apps/details?id=com.felicity.solar
