### ISSUE TITLE
No Supported Devices Found - Ecoworthy 12V 150AH (metal case version)

### ISSUE THREAD

**Issue by Scope666** [patman15/BMS_BLE-HA#169]
### Checklist

- [x] I need support with using the integration.
- [x] My issue is not a [feature request](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Feature%2BRequest&projects=&template=feature_request.yml)
- [x] I'm not avoiding to fill out the [bug report](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Bug&projects=&template=bug.yml) form.

### Describe the issue

Hi, I just setup a bluetooth proxy.  It appears to be proxying requests, and I temp installed the Bermuda BLE integration to verify I can "see" the BMS chip.  My HA setup is HA Core running in Docker on an Unraid server.  I've tried some of the bluetoothctl commands I've seen you list from inside the docker container, but they seem to hang, not sure if they work with a setup like mine.   (docker + proxy).   When I tried to add the BMS I get the "No supported devices found via bluetooth" message, and because of that the integration won't appear in HA, so can't see the normal page where your diagnostics button would be.

HA Core version:  **2025.1.4**
ESPHome version: **2024.11.3**

Here's some extra info:

ESPHome Diagnostics snippet: 
NOTE: The device name matches what you have listed as compatible:   ECO-WORTHY batteries (show up as DP..S…) ... also the UUID matches what you have in your detection code.
```
     "bluetooth": {
      "connections_free": 3,
      "connections_limit": 3,
      "available": true,
      "scanner": {
        "name": "btproxy1-815518 (3C:8A:1F:81:55:18)",
        "start_time": 1605937.150296092,
        "source": "3C:8A:1F:81:55:18",
        "scanning": true,
        "type": "ESPHomeScanner",
        "last_detection": 1606791.058140123,
        "monotonic_time": 1606791.086141202,
        "discovered_devices_and_advertisement_data": [
          {
-------SNIP---------           
            "name": "DP04S007L4S120A",
            "address": "A5:C2:37:2E:A5:C3",
            "rssi": -49,
            "advertisement_data": [
              "DP04S007L4S120A",
              {
                "42435": {
                  "__type": "<class 'bytes'>",
                  "repr": "b'.7\\xc2\\xa5'"
                }
              },
              {},
              [
                "0000ff00-0000-1000-8000-00805f9b34fb"
              ],
              -127,
              -49,
              []
            ],
            "details": {
              "source": "3C:8A:1F:81:55:18",
              "address_type": 0
            }
          },
```

HA Log:
```
2025-02-02 21:23:04.696 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to esp32-bluetooth-proxy-815518 @ 192.168.10.98 in 1.019s
2025-02-02 21:23:04.719 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successful handshake with btproxy1-815518 @ 192.168.10.98 in 0.023s
```

YAML for BT Proxy just in case:
```
esphome:

  name: btproxy1-815518
  friendly_name: Bluetooth Proxy 1
  min_version: 2024.6.0
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
logger:

ota:
  - platform: esphome
    id: ota_esphome

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
    
```

![Image](https://github.com/user-attachments/assets/a70baf57-d90e-4d4e-ae22-dd1e11bfa6a5)

<img width="928" alt="Image" src="https://github.com/user-attachments/assets/49a8073f-cd52-4952-9006-98492dad7b5c" />

<img width="922" alt="Image" src="https://github.com/user-attachments/assets/75e85085-ac57-4468-95b9-bdcec17232dd" />
