### ISSUE TITLE
No supported devices found JK BMS

### ISSUE THREAD

**Issue by mrazekfilip** [patman15/BMS_BLE-HA#184]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Please describe the enhancement you would like to have.

The integration says, "No supported devices found via Bluetooth." However, I can connect to my BMS JK_BD4A8S4P via bluetoothctl. 

Here is the information from the HA 2025.02 bluetooth integration:
```
{"name":"JK-LiFePo4","address":"98:DA:20:09:DF:DF","rssi":-73,"manufacturer_data":{"2917":"88a098da2009dfdf"},"service_data":{},"service_uuids":["00001800-0000-1000-8000-00805f9b34fb","00001801-0000-1000-8000-00805f9b34fb","0000ffe0-0000-1000-8000-00805f9b34fb"],"source":"50:84:92:26:2D:38","connectable":true,"time":1739096921.0349336,"tx_power":null}
```

blueotoothctl logs:
```
bluetoothctl connect 98:DA:20:09:DF:DF
Attempting to connect to 98:DA:20:09:DF:DF
hci2 type 6 discovering off
hci2 type 6 discovering on
[CHG] Device 18:3C:B7:F9:FC:58 RSSI: 0xffffffb0 (-80)
[CHG] Device 48:CD:ED:60:FD:C1 RSSI: 0xffffffb6 (-74)
[CHG] Device 79:75:2B:C1:19:5B RSSI: 0xffffffb8 (-72)
[CHG] Device 79:75:2B:C1:19:5B ManufacturerData.Key: 0x004c (76)
[CHG] Device 79:75:2B:C1:19:5B ManufacturerData.Value:
  0c 0e 08 65 bb 9f a3 2c 44 ef f7 e4 60 ee 0e 8d  ...e...,D...`...
  10 06 4c 1d e4 5d 65 28                          ..L..]e(        
[CHG] Device 6D:26:6B:87:B0:1C RSSI: 0xffffffbc (-68)
[CHG] Device E5:26:A7:5B:D1:55 RSSI: 0xffffffb6 (-74)
hci0 type 6 discovering off
hci0 type 6 discovering on
[CHG] Device 6B:E0:7A:AC:E6:AC RSSI: 0xffffffac (-84)
[CHG] Device 45:7B:87:F5:E9:34 RSSI: 0xffffffa2 (-94)
[CHG] Device CA:A7:48:0F:80:DF RSSI: 0xffffffb4 (-76)
[CHG] Device 49:24:BC:24:1C:8E RSSI: 0xffffffb6 (-74)
[CHG] Device 49:24:BC:24:1C:8E ManufacturerData.Key: 0x004c (76)
[CHG] Device 49:24:BC:24:1C:8E ManufacturerData.Value:
  0c 0e 08 65 bb 9f a3 2c 44 ef f7 e4 60 ee 0e 8d  ...e...,D...`...
  10 06 4c 1d e4 5d 65 28                          ..L..]e(        
[CHG] Device 98:DA:20:09:DF:DF RSSI: 0xffffffa4 (-92)
hci2 98:DA:20:09:DF:DF type LE Public connected eir_len 21
[CHG] Device 98:DA:20:09:DF:DF Connected: yes
Connection successful
```

```
bluetoothctl info 98:DA:20:09:DF:DF
Device 98:DA:20:09:DF:DF (public)
        Name: JK-LiFePo4
        Alias: JK-LiFePo4
        Paired: no
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Unknown                   (0000ffe0-0000-1000-8000-00805f9b34fb)
        ManufacturerData.Key: 0x0b65 (2917)
        ManufacturerData.Value:
  88 a0 98 da 20 09 df df                          .... ...        
        RSSI: 0xffffffa4 (-92)
```

JK_BMS information from the app:

![Image](https://github.com/user-attachments/assets/47ce30ba-0d38-4b7a-8b2b-46b064b20fd3)

I hope I didn't forget to include any logs. If you would like to know additional info, feel free to ask. Thank you.
