### ISSUE TITLE
Integrate the Supervolt batteries delivered until 23.10.2023 from the Batmon HA integration

### ISSUE THREAD

**Issue by Karatzie** [patman15/BMS_BLE-HA#57]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I use the Batmon HA integration to connect my two Supervolt batteries to HA.
The Bluetooth connection with my RPI 3 is running but stopped after short or long time.
The RPI 3 does have a high CPU load and is not able to build ESPHome firmware files.
The Bluetooth connection with my RPI 4 is very bad and I got not a connection.
My RPI 4 is placed in a metallic case with passive cooling.
I would like to use a Bluetooth Proxy to connect the RPI 4.

### Describe the solution you'd like

Please add the Supervolt BMS from Batmon HA in your integration.
I will perform the test of this connection with my both batteries.
I have a description of the communication protocol. see attachments.

### Additional context

[rs485-uart-rs232 Protocol_BT.zip](https://github.com/user-attachments/files/17175617/rs485-uart-rs232.Protocol_BT.zip)
[bms-metrisun.pdf](https://github.com/user-attachments/files/17175618/bms-metrisun.pdf)

**Comment by patman15** [comment]
Please see the README Supervolt batteries are already supported. Do you experience issues?

**Comment by Karatzie** [comment]
Hello Patrick.

Thanks for your reply.
I expected that your Supervolt integration for my batteries does not work.
I tested your integration and got the information
"Keine unterstützen Geräte via Bluetooth gefunden."
I used the RPI 3 onboard Bluetooth and not a Bluetooth proxy.

Supervolt sold three different types of LiFePo4 batteries.
**Supervolt Standard V1 2019-2023**
This battery type has a black housing cover. 
This battery type includes a E&J BMS.

**Supervolt Standard V2 2023**
This battery type has a light blue housing cover.
I don't know the BMS type.

**Supervolt Standard V3 2024**
This battery type has a light blue housing cover.
I don't know the BMS type.

I own the **Supervolt Standard V1 2019-2023**.

How can we add the **Supervolt Standard V1 2019-2023** BMS in your integration?

BR
Andreas

**Comment by patman15** [comment]
Hi Andreas! Sorry, I missed the fact that there are multiple versions, although I myself wrote only V3 is supported. 😳
So you say it worked with Batmon HA, correct? If so, I can most probably port the protocol rather quick. Thanks also for the description of the protocol, that usually helps a lot to get it working stable.
Nevertheless, I currently can't work on the integration, so I need to ask for a few weeks of patience to get started.

**Comment by Karatzie** [comment]
Hi Patrick.

My batteries can be observed with the Battmon HA.
I have some problems with the connection betwenn Battmon HA and my Supervolt battaries.
The Connection is freezing and no data will be collect from the batteries.
A repowering of the Bluetooth device of the RPi3 reconnect sometimes.
If the repowering does not work I must reboot my RPi3 completly.
After reboot of the RPi3 is it very rarely possible that the Bluetooth configuration of the RPi3 is lost.
In this case I have to delete the Bluetooth device in HA and after reboot of the RPi3 the Bluetooth device is discovered from HA.
It is a little bit complicate but I am not under pressure.
It will be a great thing if you add the Supervolt V1 in your integration.
You can perform the changes if you have time for this action.
I am looking forward and will check your solution with my batteries.

I have some remarks for you.
My campervan will be placed in a storage over the winter end of October.
It will be back in April of the next year.
It is not possible to test the integration in this period. 

BR
Andreas

**Comment by patman15** [comment]
Ok, got you! I might still have some time till end of October but can't guarantee it. Things are piling up already. 😎 Till April it should be no issue at all to get it done.

**Comment by BikeAtor** [comment]
i have a (bad) working version with support for the old black Supervolt batteries in my fork.
You can give it a try.
@patman15: you can use my code to support the old Supervolt batteries.

**Comment by patman15** [comment]
@BikeAtor thanks a lot! I might do some minor enhancements and add tests before releasing. B-)
Could you do me a favour and post the output of `bluetoothctl info <MAC address>` here?
I'd like to understand the announced characteristics of the device for proper auto-detection.

**Comment by Karatzie** [comment]
Hi Patrick.

here are the infos:
![grafik](https://github.com/user-attachments/assets/83db5394-d410-4062-ba52-a2d9e5306e57)

**Comment by BikeAtor** [comment]
My code is based upon the official doku from Bluetoothpotocol. You can get the official doku from Supervolt, but is has some minor glitches.

Am 8. Oktober 2024 18:48:34 MESZ schrieb Karatzie ***@***.***>:
>Hi Patrick.
>
>here are the infos:
>![grafik](https://github.com/user-attachments/assets/83db5394-d410-4062-ba52-a2d9e5306e57)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/patman15/BMS_BLE-HA/issues/57#issuecomment-2400366343
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Gruß, Andi

**Comment by Karatzie** [comment]
I have attached the documentation in the first post.

**Comment by BikeAtor** [comment]
I have another documentation, but the heatingpad isn't described there. So I think it's an older one.
[App_Protokoll.pdf](https://github.com/user-attachments/files/17311617/App_Protokoll.pdf)

**Comment by BikeAtor** [comment]
I have another documentation, but the heatingpad isn't described there. So I think it's an older one.

[App_Protokoll.pdf](https://github.com/user-attachments/files/17331695/App_Protokoll.pdf)

**Comment by patman15** [comment]
Started working on an implementation, but noticed that there are two different types:
[App_Protokoll.pdf](https://github.com/user-attachments/files/17311617/App_Protokoll.pdf) and [bms-metrisun.pdf](https://github.com/user-attachments/files/17175618/bms-metrisun.pdf)
The latter has all information in one frame, while the first requires 2 requests.
@BikeAtor your implementation decodes the 2 frames length 128 and 30, while the second has one frame, length 140.
@Karatzie any idea what your battery uses?
Do I need to implement both variants? :confused:

**Comment by patman15** [comment]
> I got the document directly from Supervolt for the first black batteries V1. Maybe Karatzie can test my implementation, so we know which one to implement. But I think my document will be the correct one, cause it is already working :-)

Checked against the Android app, it definitely requests both values and combines them. Funnily it ignores the remaining capacity and calculates from SoC and design capacity.

Anyway, I pushed a first working version to the branch linked to this ticket. If you want to follow my progress / help me testing (please! :blush:), you can manually install from there. Should be working fine. Need to clean up tests and I did not yet get how the CRC works. The description is ... :shushing_face:

**Comment by Karatzie** [comment]
> Started working on an implementation, but noticed that there are two different types: [App_Protokoll.pdf](https://github.com/user-attachments/files/17311617/App_Protokoll.pdf) and [bms-metrisun.pdf](https://github.com/user-attachments/files/17175618/bms-metrisun.pdf) The latter has all information in one frame, while the first requires 2 requests. @BikeAtor your implementation decodes the 2 frames length 128 and 30, while the second has one frame, length 140. @Karatzie any idea what your battery uses? Do I need to implement both variants? 😕

Hi Patrick.

I got the APP_protokoll.pdf from Supervolt Customer Service.

I searched for the string
![grafik](https://github.com/user-attachments/assets/d3078ff2-ab45-4945-8531-687a9c0568f3)
and found the same string in the BMS-Meritsum.pdf in GITHUB.
It is possible that your BMS_BLE-HA  also works with Meritsum.
I belive that the code of the batmon-ha integration is based on the code from @BikeAtor.

I will test your test version.
Thank you for your effort.

BR
Andreas

**Comment by BikeAtor** [comment]
First try: didn't work

Changed libatt to libatt* in manifest and ej-bms -> didn't work
Removed maufacturer id and service_uuid in both files -> Working!!

I will try to to see if manufacturer id can be added again.

**Comment by BikeAtor** [comment]
Ok, with these changes it is running:

manifest.json (added *):
```
{
      "local_name": "libatt*",
      "service_uuid": "0000fff0-0000-1000-8000-00805f9b34fb",
      "manufacturer_id": 21320
    }
```

ej_bms.py (added *, removed service_uuid)
```
def matcher_dict_list() -> list[dict[str, Any]]:
        """Provide BluetoothMatcher definition."""
        return [
            {
                "local_name": "libatt*",
                "manufacturer_id": 21320,
                "connectable": True,
            }
        ]
```

**Comment by BikeAtor** [comment]
![grafik](https://github.com/user-attachments/assets/7436e983-f9a5-4cb8-96df-c11a15dde050)

**Comment by Karatzie** [comment]
How can I install the BMS_BLE-HA localy?

**Comment by BikeAtor** [comment]
I checked out branch "57-integrate-supervolt-batteries-v1" to my local computer and copied the files to my HA-instance.

It should be working in HA in the Advanced Terminal as well.

Maybe (not sure if last cp is right):
```
mkdir tmp
cd tmp
git clone https://github.com/patman15/BMS_BLE-HA.git
cd BMS_BLE-HA
git switch 57-integrate-supervolt-batteries-v1
cp -r custom_components/bms_ble/* ../../config/custom_components/bms_ble/
```

And don't forget to make the changes from my Post. I use "Studio Code Server" to edit files in HA.

**Comment by BikeAtor** [comment]
No, there is no really need for it. If some more files are there it doesn't matter. I wanted to keep my own implementation there. So I just did copy the new files over the old ones.

But you can do it if you like. All needed files are checked out from git. And HA only looks for the files. There is no other database.

**Comment by BikeAtor** [comment]
Here are my changes to configuration.yaml
```
template:
  # Supervolt cell voltages
  - sensor:
      - name: cell_voltage_1_0
        state: >-
          {{ state_attr('sensor.libatt55b4_delta_voltage', 'cell_voltages')[0] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt55b4_delta_voltage') }}
  - sensor:
      - name: cell_voltage_1_1
        state: >-
          {{ state_attr('sensor.libatt55b4_delta_voltage', 'cell_voltages')[1] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt55b4_delta_voltage') }}
  - sensor:
      - name: cell_voltage_1_2
        state: >-
          {{ state_attr('sensor.libatt55b4_delta_voltage', 'cell_voltages')[2] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt55b4_delta_voltage') }}
  - sensor:
      - name: cell_voltage_1_3
        state: >-
          {{ state_attr('sensor.libatt55b4_delta_voltage', 'cell_voltages')[3] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt55b4_delta_voltage') }}

  - sensor:
      - name: cell_voltage_2_0
        state: >-
          {{ state_attr('sensor.libatt0ffc_delta_voltage', 'cell_voltages')[0] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt0ffc_delta_voltage') }}
  - sensor:
      - name: cell_voltage_2_1
        state: >-
          {{ state_attr('sensor.libatt0ffc_delta_voltage', 'cell_voltages')[1] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt0ffc_delta_voltage') }}
  - sensor:
      - name: cell_voltage_2_2
        state: >-
          {{ state_attr('sensor.libatt0ffc_delta_voltage', 'cell_voltages')[2] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt0ffc_delta_voltage') }}
  - sensor:
      - name: cell_voltage_2_3
        state: >-
          {{ state_attr('sensor.libatt0ffc_delta_voltage', 'cell_voltages')[3] }}
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        availability: >-
          {{ has_value('sensor.libatt0ffc_delta_voltage') }}
```

And in lovolace raw editor:
```
  - title: Supervolt
    path: supervolt
    type: sidebar
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.libatt55b4_batterie
            name: SOC
            hours_to_show: 24
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.libatt0ffc_batterie
            name: SOC
            hours_to_show: 24
      - type: horizontal-stack
        cards:
          - type: entities
            title: Supervolt1
            entities:
              - entity: sensor.libatt55b4_batterie
                name: Batterie
                secondary_info: last-changed
              - entity: sensor.libatt55b4_gespeicherte_energie
                name: Gespeicherte Energie
              - entity: sensor.libatt55b4_leistung
                name: Leistung
                secondary_info: last-changed
              - entity: sensor.libatt55b4_spannung
                name: Spannung
              - entity: sensor.libatt55b4_stromstarke
                name: Stromstärke
              - entity: sensor.libatt55b4_temperatur
                name: Temperatur
          - type: entities
            title: Supervolt2
            entities:
              - entity: sensor.libatt0ffc_batterie
                name: Batterie
                secondary_info: last-changed
              - entity: sensor.libatt0ffc_gespeicherte_energie
                name: Gespeicherte Energie
              - entity: sensor.libatt0ffc_leistung
                name: Leistung
                secondary_info: last-changed
              - entity: sensor.libatt0ffc_spannung
                name: Spannung
              - entity: sensor.libatt0ffc_stromstarke
                name: Stromstärke
              - entity: sensor.libatt0ffc_temperatur
                name: Temperatur
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.cell_voltage_1_0
            name: Zelle 0
          - type: sensor
            entity: sensor.cell_voltage_1_1
            name: Zelle 1
          - type: sensor
            entity: sensor.cell_voltage_1_2
            name: Zelle 2
          - type: sensor
            entity: sensor.cell_voltage_1_3
            name: Zelle 3
          - type: sensor
            entity: sensor.cell_voltage_2_0
            name: Zelle 0
          - type: sensor
            entity: sensor.cell_voltage_2_1
            name: Zelle 1
          - type: sensor
            entity: sensor.cell_voltage_2_2
            name: Zelle 2
          - type: sensor
            entity: sensor.cell_voltage_2_3
            name: Zelle 3
      - type: horizontal-stack
        cards:
          - type: history-graph
            title: Zellspannungen 1
            entities:
              - entity: sensor.cell_voltage_1_0
                name: Zelle 0
              - entity: sensor.cell_voltage_1_1
                name: Zelle 1
              - entity: sensor.cell_voltage_1_2
                name: Zelle 2
              - entity: sensor.cell_voltage_1_3
                name: Zelle 3
            hours_to_show: 24
          - type: history-graph
            title: Zellspannungen 2
            entities:
              - entity: sensor.cell_voltage_2_0
                name: Zelle 0
              - entity: sensor.cell_voltage_2_1
                name: Zelle 1
              - entity: sensor.cell_voltage_2_2
                name: Zelle 2
              - entity: sensor.cell_voltage_2_3
                name: Zelle 3
            hours_to_show: 24
```
